/**
 * クイック作成用テンプレのフォールバック。
 * content/quick/menu-templates-9.json が読めない場合に使用する（ビルドに同梱される）。
 */
export const menuTemplates9Fallback = {
  S: [
    {
      purpose: '力みを抜き、最もスムーズに進むポジション再確認',
      warmUp: 'W-up 200m（A1）',
      drill: 'IM order（Drill/Swim） 4×100m（EN1）',
      kick: 'Kick cho 6×50m（EN2）｜good kick',
      pull: 'Pull cho 8×50m（EN2）｜Form',
      preMain: 'Pre-Main FR 8×50m（EN2）｜1-4 Dec good form',
      dive: '',
      rest: 'Rest 100m（A1）',
      main: 'Main S1 2×25m（Hard）',
      down: 'W-down 150m（A1）',
      total: '合計距離：2,000m',
      intention: '余計な力みを抜き、最もスムーズに進むポジションを再確認。',
      coachingPoint: '短い距離でも、浮き上がり〜フィニッシュまで"スピードに乗る感覚"を大切に。',
      caution: 'リラックスする場面と、パッと集中する場面の切り替えを意識。',
      expectedEffect: 'ショート種目での推進効率と加速感の改善。',
    },
    {
      purpose: 'スピードを上げても崩れない低抵抗ポジション定着',
      warmUp: 'W-up 200m（A1）',
      drill: 'IM order 4×100m（EN1）',
      kick: 'Kick S1 3×100m（EN2）｜good kick',
      pull: 'Pull FR 10×50m（EN2）｜1-5 Des DPS',
      preMain: 'Pre-Main FR 4×100m（EN2）｜1-4 Dec good form',
      dive: '',
      rest: 'Rest 100m（A1）',
      main: 'Main S1 4×25m（EN3）｜1E/2H Alt',
      down: 'W-down 300m（A1）',
      total: '合計距離：2,300m',
      intention: 'スピードを上げても泳ぎが崩れない、抵抗の少ないポジションを体に覚え込ませる。',
      coachingPoint: 'Pullはテンポに頼らず"一掻きで進む距離（DPS）"を伸ばす意識。',
      caution: '「力任せ」ではなく「正しい動作の結果」としてスピードを出す。',
      expectedEffect: '短距離でのフォーム維持力・スピードアップ時の安定性向上。',
    },
    {
      purpose: '最大スピード局面でもフォームを崩さず推進力に変える',
      warmUp: 'W-up 200m（A1）',
      drill: 'IM re 50m Drill/50m Swim 4×100m（EN1）',
      kick: 'Kick S1 10×50m（EN2）｜1-4 Dec, 5 Hard Alt',
      pull: 'Pull FR 6×100m（EN2）｜B-up',
      preMain: 'Pre-Main FR 6×50m（EN2）｜1-3 Dec Alt',
      dive: '',
      rest: 'Rest 100m（A1）',
      main: 'Main S1 12×50m（EN3）｜1H/1E Alt',
      down: 'W-down 300m（A1）',
      total: '合計距離：3,000m',
      intention: 'スピードが最大に達した局面でも、フォームを崩さず推進力に変える技術を確認。',
      coachingPoint: '本数が多いが、Hardはスタートから"爆発的出力"を出し切る意識。',
      caution: '負荷が高いので、肩・腰の違和感があれば即強度ダウン判断。',
      expectedEffect: 'ショートのレース局面（最大スピード帯）でのフォーム耐性が上がる。',
    },
  ],
  M: [
    {
      purpose: '「楽に速く泳ぐ」効率フォーム再確認',
      warmUp: 'W-up 400m（A1）',
      drill: 'IM odd: pull / even: kick 6×50m（EN1）',
      kick: 'Kick cho 8×50m（EN2）｜good kick',
      pull: 'Pull cho 12×50m（EN2）｜Form',
      preMain: 'Pre-Main FR 12×50m（EN2）｜1-4 Dec good form',
      dive: '',
      rest: 'Rest 100m（A1）',
      main: 'Main S1 2×25m（Hard）',
      down: 'W-down 200m（A1）',
      total: '合計距離：2,650m',
      intention: 'ミドルに必要な「楽に速く泳ぐ」ための効率の良いフォームを再確認。',
      coachingPoint: '25m Hardは、持久的疲れを残さない範囲で"連動性と乗り"をチェック。',
      caution: '疲労で腰が落ちたり乱れるなら、距離調整してでも「良い姿勢」優先。',
      expectedEffect: '100〜400mのレース対応力（効率×安定）の向上。',
    },
    {
      purpose: '距離を泳いでも崩れない低抵抗姿勢の定着',
      warmUp: 'W-up 600m（A1）｜mixed(200m Swim/200m Kick/200m Pull)',
      drill: 'IM odd: Drill / even: Swim 8×50m（EN1）',
      kick: 'Kick S1 4×100m（EN2）｜good kick',
      pull: 'Pull FR 15×50m（EN2）｜1-5 Des DPS',
      preMain: 'Pre-Main FR 6×100m（EN2）｜1-3 Dec good form Alt',
      dive: '',
      rest: 'Rest 100m（A1）',
      main: 'Main S1 4×25m（EN3）｜1E/2H Alt',
      down: 'W-down 300m（A1）',
      total: '合計距離：3,250m',
      intention: '距離を泳いでも崩れない、抵抗の少ない姿勢を体に定着させる。',
      coachingPoint: '本数が増えても、DPS（進む距離）を落とさない意識。',
      caution: '距離に流されず、一掻きごとの感覚を大切にする。',
      expectedEffect: 'ミドル域でのフォーム持久力と効率の底上げ。',
    },
    {
      purpose: '心拍が上がっても無駄を抑え、安定して泳ぎ続ける',
      warmUp: 'W-up 400m（A1）',
      drill: 'IM reverse 1×200m（EN1）',
      kick: 'Kick S1 15×50m（EN2）｜1-4 Dec, 5 Hard Alt',
      pull: 'Pull FR 8×100m（EN2）｜B-up',
      preMain: 'Pre-Main FR 9×50m（EN2）｜1-3 Dec Alt',
      dive: '',
      rest: 'Rest 100m（A1）',
      main: 'Main S1 12×50m（EN3）｜1H/1E Alt',
      down: 'W-down 300m（A1）',
      total: '合計距離：3,600m',
      intention: '心拍数が上がった状態でも、無駄な動きを抑えて進む感覚を覚え込ませる。',
      coachingPoint: 'メイン前にB-upやHard Kickで体を動かし"出力できる状態"に整える。',
      caution: '疲労で雑になりやすいので、スピードを出しつつも「丁寧なキャッチ」徹底。',
      expectedEffect: 'ミドルのレース後半での粘り・安定（心拍高でも崩れない）。',
    },
  ],
  D: [
    {
      purpose: '低燃費フォームを取り戻し、長距離でも楽にスピード維持',
      warmUp: 'W-up 400m（A1）',
      drill: 'IM order(25m drill/25m swim) 8×50m（EN1）',
      kick: 'Kick cho 10×50m（EN2）｜good kick',
      pull: 'Pull cho 8×100m（EN2）｜Form',
      preMain: 'Pre-Main FR 8×100m（EN2）｜1-4 Dec good form',
      dive: '',
      rest: 'Rest 100m（A1）',
      main: 'Main S1 2×25m（Hard）',
      down: 'W-down 200m（A1）',
      total: '合計距離：3,250m',
      intention: '長い距離の中で無駄な力みを抜き、最も楽にスピードが出る「低燃費フォーム」を取り戻す。',
      coachingPoint: '25m Hardは疲労を溜めない範囲で"体のキレ"だけ呼び起こせばOK。',
      caution: '距離が長くても腰位置を高く保ち、低抵抗姿勢を維持し続ける集中力。',
      expectedEffect: '長距離での省エネ泳法と巡航スピードの改善。',
    },
    {
      purpose: '低抵抗フォームを"維持し続ける力"を養う',
      warmUp: 'W-up 400m（A1）',
      drill: 'IM reverse 1×200m（EN1）',
      kick: 'Kick S1 6×100m（EN2）｜good kick',
      pull: 'Pull FR 10×100m（EN2）｜1-5 Des DPS',
      preMain: 'Pre-Main FR 8×100m（EN2）｜1-4 Dec good form',
      dive: '',
      rest: 'Rest 100m（A1）',
      main: 'Main S1 4×25m（EN3）｜1E/2H Alt',
      down: 'W-down 300m（A1）',
      total: '合計距離：3,500m',
      intention: '長い距離の中でも疲労に負けず、低抵抗で効率の良いフォームを維持し続ける力を養う。',
      coachingPoint: '100m×10 Pullは、本数を重ねてもストローク数が変わらないよう"一掻きの精度"に集中。',
      caution: 'ただ距離をこなすのではなく、一掻きごとに「考えて泳ぐ」を徹底。雑なら即修正。',
      expectedEffect: '長距離の巡航でのフォーム再現性・効率維持力アップ。',
    },
    {
      purpose: '速いペースでもフォームを崩さず安定して泳ぎ続ける',
      warmUp: 'W-up 200m（A1）',
      drill: 'IM scull / swim 2×100m（EN1）',
      kick: 'Kick S1 20×50m（EN2）｜1-4 Dec, 5 Hard Alt',
      pull: 'Pull FR 10×100m（EN2）｜B-up',
      preMain: 'Pre-Main FR 12×50m（EN2）｜1-3 Dec Alt',
      dive: '',
      rest: 'Rest 100m（A1）',
      main: 'Main S1 10×100m（EN3）｜1H/1E Alt',
      down: 'W-down 300m（A1）',
      total: '合計距離：4,400m',
      intention: '速いペースの中でもフォームを崩さず、安定して泳ぎ続ける力をつける。',
      coachingPoint: '各100m Hardでタイムを安定させ、レースを想定した"粘り強い泳ぎ"を促す。',
      caution: '距離と強度が重なるため、怪我や過度な疲労がないか選手の様子を細かく観察。',
      expectedEffect: 'ディスタンスのレース後半（高強度×長時間）での安定と粘りが上がる。',
    },
  ],
} as const;
